[env:seeed_xiao_esp32c3]
platform  = espressif32
board     = seeed_xiao_esp32c3
framework = arduino

monitor_speed = 115200
monitor_port = COM8
monitor_dtr = 0
monitor_rts = 1

lib_deps =
    adafruit/Adafruit PCF8574 @ ^1.0.0
    knolleary/PubSubClient   @ ^2.8
    bblanchon/ArduinoJson    @ ^7.0

board_build.partitions = custom_partitions.csv
board_build.filesystem = littlefs

build_flags =
    -D FIRMWARE_VERSION=\"1.1.0\"
    -D GITHUB_OWNER=\"bugi67\"
    -D GITHUB_REPO=\"GT-JC-4s\"
    -D CONFIG_FREERTOS_UNICORE=1
    -D LOG_LEVEL_DEFAULT=2
    -D ARDUINO_USB_CDC_ON_BOOT=1

upload_protocol = esptool
upload_port = COM8
